### ISSUE TITLE
stream parsing support

### ISSUE THREAD

**Issue by df2218380513f49d8a3d896fc45740e9** [ColinH/PEGTL#15]
Is it possible to parse true (unseekable, possibly infinite) streams with PEGTL?

For example, could the calculator demo be modified to parse stdin as a stream, with 'quit' being a parser action?

In my particular case, I have a growing number (1000s) of large (~200GB) files. The files are stored compressed and accessed over a network. I would like to decompress these and pipe the uncompressed stream directly to the parser, to avoid the time penalty associated with decompressing to temporary files just so that they can be parsed. Sadly, I can't decompress entire files into memory and parse them that way, and "chunking" them is not as simple as splitting on newlines (as in the calculator demo).

**Comment by ColinH** [comment]
The short answer is: No, it is currently not possible, however:

It is something that the pre-2014-refactoring PEGTL was more-or-less capable of, and we had always planned on looking into bringing this feature back in a well-defined fashion if and when there was demand.

(We left it out during the refactoring because it was a bit of a hassle, we wanted to make the simple cases as simple as possible, and we weren't sure whether it was actually needed -- in all the years we ourselves didn't. There is also the question of whether a co-routine based approach would be useful when generalising to blocking inputs like sockets...)

An a more technical note, the original approach used the structure of the grammar to automatically decide which part of the input, i.e. how far back, to buffer, in order to allow whatever backtracking the grammar might perform. It did not however consider actions, or which part of the input will be required to invoke an action.

I'd have to think about this again, taking into consideration the changes to the library done in the refactoring. Do you already have a grammar to look at and use as an example?

**Comment by df2218380513f49d8a3d896fc45740e9** [comment]
OK, I see.

Re: grammar, I haven't coded anything up yet (due to this very issue) but it is Cadence's proprietary DEF format, defined here (warning: copyright): www.ispd.cc/contests/14/web/doc/lefdefref.pdf . Having said that, DEF is really just a very simple "tree-like" language, so the parser will be about as simple as they come.

Re: co-routines, I'm not sure what to say.

What feels reasonable in this particular case would be a way to request that PEGTL parse some number of bytes, and return the number of bytes successfully parsed. I could then write a loop that fetches some fixed amount of compressed data, unpacks it and attempts to parse it. In general some fraction of the data would remain unmatched and it would be up to me to just grow the input buffer and try again.

This leaves the issue of PEGTL's buffering. Would it be reasonable to define a way for users to tell PEGTL that when a "chunk" is successfully matched, it will never need to go backwards beyond that point? For example, would it be reasonable to support something like:

struct Section : sor<AB, checkpoint<CD>, EF> {};
struct File : star<Section> {};

where 'checkpoint<CD>' means that if a 'CD' element is matched, PEGTL can drop its buffer?

**Comment by ColinH** [comment]
Yes, that's exactly the direction that I'm looking at, while trying to minimise the impact on the rest of the library.

The basic parsing rules will have to tell the buffered input how many bytes they need, and if that's beyond the current buffer contents then the buffered input asks a user-supplied reader for more data.

And yes, the grammar will have to tell the buffered input when it can discard all previously consumed input bytes because neither backtracking nor actions will ever need that data again.

(Later we could check whether the buffer clearing can be automated like in the "old" PEGTL, however we can't use the old approach because some key things have changed, and because actions weren't considered. To simplify we should leave it out for now, just like co-routines, which would be useful for situations like one thread parsing data from multiple network sockets.)

As far as I can see the user-supplied reader only needs to have a `size_t read( void *, size_t )` method with the convention that if the return value is less than the second argument then end-of-file was reached.

**Comment by df2218380513f49d8a3d896fc45740e9** [comment]
OK, I understand, and agree that that reader convention will do the trick.

If there's anything I can do to help, please let me know. Otherwise, I look forward to seeing what you come up with and trying it out!

**Comment by ColinH** [comment]
A first prototype is up-and-running, if you contact us at `pegtl(at)colin-hirsch.net` you can give it a try (there are still a few corners that need to be looked into and polished before making a release).

**Comment by ColinH** [comment]
The prototype code works for @df2218380513f49d8a3d896fc45740e9 and, with a few more refinements, will most likely go into the next major release.

**Comment by ColinH** [comment]
A slightly evolved version is in the master branch now with:

- Class `buffer_input` works as in the prototype with arbitrary custom readers.
- New `parse()`-functions and readers are supplied for C and C++ streams etc.
- A separate input class for actions' `apply()`-method catches some errors at compile time.

Documentation will follow when everything is stable for a new release.

**Comment by ColinH** [comment]
The documentation is more or less finished, I will now close this issue.

**Comment by rayglover** [comment]
@ColinH Thank you for the Incremental-input API, I've been experimenting with it and I have a few questions. You mention co-routines and that seems vaguely relevant to my use case.

My application is running on an event loop and is processing a large (multi GB) log stream over a network asynchronously. I plan to use PEGTL to process the stream incrementally, in a non-blocking fashion.

I'm looking for the best strategy; it doesn't seem like the `std::size_t( char *, const std::size_t )` API suffices here because I need to either push data to the parser, or be able to communicate that the paring needs to pause (or yield) and then be _resumed_ once more data is available (like a co-routine.)

I've read `buffer_input.hh` but it doesn't seem obvious to me that a yield/resume approach could be implemented there, but then again I don't have much experience with PEGTL.

The alternative is that I move the parsing on to thread-pool, along with any blocking operations, but that seems fairly sub-optimal.

Thank you for any advice.

**Comment by ColinH** [comment]
Yes, the classical coroutine approach for producer-consumer is that you have one coroutine running the producer, and one coroutine running the consumer. Whenever the consumer needs more data than is available, you switch to the producer until it has something new to give to the consumer.

With the PEGTL and its `buffer_input`, the correct place to yield to another coroutine would be in the custom `Reader` passed to the `buffer_input`, however I have to admit to not having tried this yet so I can't say how well it works in practice or which coroutine library to use.

Assuming that you want to manage more than one socket with a single thread (otherwise you could really just wait for the socket in the `Reader`) I would try to run the mainloop/reactor/selector in the "main" coroutine of the thread, and spawn a coroutine for each parsing run.

Luckily there does seem to be more interest in coroutines lately, I just saw that there is a new C++11 "Coroutine2" library in Boost, that should be a good starting point. Don't hesitate to ask if you have further questions on how to use coroutines - or just let us know how it's going!

**Comment by rayglover** [comment]
Thanks for the advice. I have a few ideas now. I'll let you know if anything comes of it.

I'm not *actually* using a co-routine library and all the extra baggage that comes with, but I believe my problem is abstractly the same; I'm actually using libuv but that's really an implementation detail.

**Comment by lambdafu** [comment]
I'll also be looking into coroutines.  My use case is implementing OpenPGP, which allows for nested data streams (compressed data in encrypted data in a larger structure).  The data can be of indeterminate length using chunks.  There is no backtracking, and data can be discarded regularly, but there can be several (let's say three) parsers running in parallel, one feeding the next (through an intermediate filter that does the actual decryption or decompression).
Ideally, there would be a push-interface for pegtl, but I agree that it should be possible to build with coroutines. I'll report here.

**Comment by ColinH** [comment]
Thank you for the update, we’d be very interested to see what you are building!
