### ISSUE TITLE
missing expression.cc example?

### ISSUE THREAD

**Issue by skyrich62** [ColinH/PEGTL#34]
Hi,

First, wow!  Kudos to you, this is very cool.

Your documentation says that there should be examples/expression.cc which is the same as the calculator example, but builds an parse tree and operates on that.  I'm either incredibly blind, or it's not in the examples directory.

I'd really like to see a good example of how to build a parse tree with this parser.

**Comment by ColinH** [comment]
The file actually exists, unfortunately I can't remember why it was taken out of the examples directory. Take a look, see whether it works, report back, and if it does work we might put it back. It doesn't seem to be the most readable example in the world, which could be the reason we got rid of it :-)

[expression.txt](https://github.com/ColinH/PEGTL/files/612026/expression.txt)

**Comment by ColinH** [comment]
We just discussed this issue, the expression example was removed because, as you can see, it is not particularly readable and doesn't show how to build an AST in a nice way - it was more an experiment in how to handle the operators.

For now, I will remove the reference to it in the documentation; we already have "make a nice AST example" on our TODO list and will hopefully get around to doing this soon.
