### ISSUE TITLE
REQ: stop parsing from action

### ISSUE THREAD

**Issue by cppden** [ColinH/PEGTL#47]
I understand that it's possible to abort parsing by throwing an exception but it would be nice to have ability to stop parsing depending on `action` result.
E.g., instead of current signature an `action` can also return result:
```cpp
template<> struct action< SOME >
{
  template <class T, class... ARGS>
  static bool apply(T const& in, ARGS&&...)
  {
    if (CONDITION) return false;
    return true;
  }
};
```

**Comment by d-frey** [comment]
When you say "stop" parsing instead of "abort" parsing (with an exception), what do you mean by that? Should the action be able to turn a match into a non-match? IOW, continue parsing but let the local rule fail depending on the action and then let parsing continue the usual way?

**Comment by cppden** [comment]
By "stop" I mean that any further parsing will stop and entry `parse` function will return false. It's not about turning a local failure into a global failure but rather a global failure w/o exception.

**Comment by ColinH** [comment]
In PEGTL terminology a global failure *is* an exception, so a global failure without one is not possible. Local failure is a return value of `false` from a rule's `match()`-function, which, in the absence of `must<>`, might or might not propagate up to the original `parse()`-function depending on the grammar and its backtracking etc.
It is currently a deliberate design decision to *not* have `apply()` return a `bool` like `match()` does, due to both technical and conceptual issues. However we will take this occasion to briefly revisit the subject, but first let me clarify:
Would this solve your issue, or do you really need a "*global* failure without exception"?
And: The current way to handle the rare cases where an action needs to return `true` or `false` like `match()` is to create a custom rule that also performs the action.

**Comment by cppden** [comment]
I see. If this is a design decision then no need to break it. I will raise an exception then (this time it's definitely a rare case).
Thanks a lot!

**Comment by d-frey** [comment]
To add, throwing an exception and catching it several levels above can even be *more* efficient than having to check a return value (especially when the return value hits a branch misprediction). For the PEGTL, this is even more true since some levels might benefit from the knowledge that some part of the grammar must return true or throw an exception. We then omit some position markers which lead to additional overhead otherwise.

Finally, you can also control how far exceptions are propagated in your grammar, by catching them at any rule and turning them into a local failure. Check out the [`try_catch`](https://github.com/ColinH/PEGTL/blob/master/doc/Rule-Reference.md#try_catch-r-)-rule or the [`try_catch_type`](https://github.com/ColinH/PEGTL/blob/master/doc/Rule-Reference.md#try_catch_type-e-r-)-rule. If you place the rule at your grammar's top-level, you will not see exceptions on the outside, they will be used internally only.

**Comment by cppden** [comment]
I tend to agree with you on possible overhead caused by tracking position. Though it can be as simple as offset in input buffer which is present and tracked anyway. But it's really hard for me to imagine proper usage of try/catch rules since I still believe the exceptions are for exceptional cases, i.e. something went so wrong that we have to let go the current execution flow hoping the layer above knows how to proceed. Such rules within grammar seem to encourage usage of exceptions in a wrong way to control execution within the same layer...

**Comment by d-frey** [comment]
The input markers in our case usually consist of the byte offset within the input, the line number, the byte within the line (aka column, except UTF-8 != byte) and the actual pointer to the position. That's 32 bytes on a 64-bit machine. We know that e.g. Clang uses more sophisticated ways to do this (only storing a single 32-bit value), but this can not be easily generalized.

We are considering other options like dropping everything except the actual pointer as it is everything the parser itself actually needs and you could rescan the input (file/memory string/...) to figure out the line number, etc. only in case you actually need it, including the complete line where the error occurred. This might optimize the good-case while simultaneously pessimizing the exceptional case. We don't have any concrete proposal for this yet.

One word about using exception handling only in exceptional cases: I guess it boils down to a dogmatic vs. a pragmatic view, at least for me. While traditionally exceptions where slow to the point where you should really avoid having them within the normal expected behavior of your code, there has been a lot of progress and optimizations and nowadays I see them as a tool like any other feature of the language. For the PEGTL we think it is the right tool for global failures for 99% of the users/cases, where "returning" from a deeply nested call stack is required. If it really turns out to be an actual problem (proven by measurements), I don't think having a simple boolean as the return value from `apply()` would be the appropriate solution. The rules' `match()` method would be more suitable, but for now we don't really see this as a generally needed use case. If you can provide some real-world example where it would matter, we will of course have a look at it - but an artificial benchmark is not enough for me personally.

**Comment by cppden** [comment]
Thank you for sharing your thouhgts on this.
IMHO, there's no need to store and update anything except the current offset in input bufer (i.e. the pointer `char const*`). If user needs info in terms of line and column then external functions can be provided to calculate it. I believe this will noticeably improve overall performance.
Regarding the exceptions you may be right about latest optimizations when exception isn't thrown but AFAIR, when exception is thrown the performance penalty is still rather significant. Thus my "dogmatic" pov seems more logical in terms of performance.

Just in case, since my idea to stop parsing from action contradicts the design and is naturally correspond to exceptional case, I can't and *won't* provide any real-world example. :)
Thanks!

**Comment by cppden** [comment]
Just got another idea. What if the parsing function will accept input range (begin, end) and return iterator to the last parsed position? This way a user can switch between grammars and/or determine himself if he's reached the end or not. Also this way you simultaneously get the error position when it != end (only the failing rule info is missing). Seems pretty flexible and stl-looking ;)

**Comment by ColinH** [comment]
Your intuition regarding the performance of exceptions is correct for older but not too-old compilers. In the beginning both try-catch and throw were expensive. Then they managed to optimise try-catch to zero cost. Nowadays performance is no reason against throwing exceptions anymore.

Anyhow, regarding your suggestions, there is one problem: They are not compatible with the recently introduced incremental or streaming parsing, where not the whole input is available in-memory at once.

We have thought about removing the streaming parsing again, which would allow such optimisations, but on the other hand some people really are parsing enormous chunks of data that they can't read or mmap all at once...

Another alternative is to make this part flexible, however there are many details that make this more difficult than might seem at first sight.

**Comment by cppden** [comment]
Hi again guys! Still enjoing your PEGTL (really saved so much time and nerves). So thank you one more time! 🥇 
Our discussion made me refresh my knowledge on exceptions. Indeed the table based approach makes try/catch for free. After proving it with benchmark I've extended my MED library to support exceptions. Below is the benchmark results for you to consider.
As you can see when exception is thrown the performance penalty is huge. In my tests it's 300..500 times slower than old vanilla if/else.
On the other hand when no exception is thrown it's 1.2-3 times faster than if/else.
Error handling via **exceptions**:
```
Benchmark               Time           CPU Iterations
-----------------------------------------------------
BM_encode_ok           16 ns         16 ns   43763287
BM_encode_fail       2893 ns       2887 ns     243108
BM_decode_ok           15 ns         15 ns   45953136
BM_decode_fail       3538 ns       3532 ns     198163
```
Error handling via **if/esle**:
```
Benchmark               Time           CPU Iterations
-----------------------------------------------------
BM_encode_ok           50 ns         49 ns   12869271
BM_encode_fail          6 ns          6 ns  105444089
BM_decode_ok           18 ns         18 ns   37576359
BM_decode_fail         12 ns         12 ns   57652119
```

**Comment by ColinH** [comment]
Hi, and thanks for the kind words :-)  It's quite nice how cheap try-catch is, whereas the if-else always incurs some cost. That, together with wide-spread RAII, makes it easy to keep the code clean and to avoid the if-else cascades so typical of some C code.
